### ISSUE TITLE
ubuntu 22.04安装失败 

### ISSUE THREAD

**Issue by xvim** [jonssonyan/install-script#2]
正在读取软件包列表... 完成
W: https://mirrors.aliyun.com/kubernetes/apt/dists/kubernetes-xenial/InRelease: 密钥存储在过时的 trusted.gpg 密钥环中（/etc/apt/trusted.gpg），请参见 apt-key(8) 的 DEPRECATION 一节以了解详情。
W: 无法下载 https://qv2ray.net/debian/dists/stable/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 64.91.249.20 443]
W: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。
E: 不能理解命令行选项 “--disableexcludes=kubernetes” 与其他选项的搭配
bash: /etc/sysconfig/kubelet: 没有那个文件或目录
Failed to enable unit: Unit file kubelet.service does not exist.
---> k8s安装失败

**Comment by jonssonyan** [comment]
W: 无法下载 https://qv2ray.net/debian/dists/stable/InRelease 这一步在下载qv2ray.net的文件，但是qv2ray.net这个域名早就不用了，因为qv2ray已经停止维护了。

**Comment by xvim** [comment]
qv2ray这个源拿掉了还是不行的，是前面一个签名错误

升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 27 个软件包未被升级。
获取:1 https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial InRelease [8,993 B]
命中:2 http://mirrors.huaweicloud.com/repository/ubuntu jammy InRelease                                                        
命中:3 http://mirrors.huaweicloud.com/repository/ubuntu jammy-updates InRelease                                                
错误:1 https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial InRelease                   
  由于没有公钥，无法验证下列签名： NO_PUBKEY B53DC80D13EDEF05
命中:4 http://mirrors.huaweicloud.com/repository/ubuntu jammy-backports InRelease
命中:5 https://download.docker.com/linux/ubuntu jammy InRelease  
命中:6 http://mirrors.huaweicloud.com/repository/ubuntu jammy-security InRelease
命中:7 http://archive.ubuntu.com/ubuntu jammy InRelease
正在读取软件包列表... 完成
W: GPG 错误：https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY B53DC80D13EDEF05
E: 仓库 “https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial InRelease” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
E: 不能理解命令行选项 “--disableexcludes=kubernetes” 与其他选项的搭配
bash: /etc/sysconfig/kubelet: 没有那个文件或目录
Failed to enable unit: Unit file kubelet.service does not exist.
---> k8s安装失败

**Comment by jonssonyan** [comment]
DD系统用ubuntu官网最新的镜像试试，我测试是用的VirtualBox+官方ISO文件装的系统测试的。
