### ISSUE TITLE
aarch64架构的Linux安装出错

### ISSUE THREAD

**Issue by lovemoqing** [jonssonyan/install-script#3]
我的本地环境是MacOS(M1芯片)安装的CentOS9，aarch64架构的Linux一键脚本会提示找不到安装包
后面研究了一下，发现是镜像源的问题，脚本里给的镜像源baseurl这个字段都是x86_64，应该判断一下，如果是aarch64架构的Linux，镜像源应该设置为baseurl=http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-aarch64/
除了这个暂时没有别的问题，博主的一键脚本还是挺好用的， 因为我在我的云服务器上面跑通了，hahaha

**Comment by jonssonyan** [comment]
可以的👍，已经改好提交了。
